Dota2_Assistant/urls.py
"""
Definition of urls for Dota2_Starter_Purchase_Assistant.
"""

from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('Home/', include('home.urls')),
    path('matches/', include('match_history.urls')),
    path('Matches/', include('match_history.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from home import views

app_name = 'Assistant_Home'

urlpatterns = [
    path('', views.StartPadge, name='StartPadge'),
    ]

match_history/urls.py
from django.urls import path, include
from match_history import views

app_name = 'Matches'

urlpatterns = [
	path('Page<int:page_number>', views.GetMatches, name = 'GetMatches'),
	path('update_heroes', views.Update_Hereos, name='update_heroes'),
	path('update_items', views.Update_Items, name='update_items'),
	]

home/models.py
from django.db import models

# Create your models here.

match_history/models.py
from django.db import models

class Item(models.Model):
    JSON_Data = models.JSONField('Item data in JSON format', 'Data')
    pass


class Hero(models.Model):
    Name = models.TextField("Hero Name", "Name", default="Hero")
    JSON_Data : models.JSONField = models.JSONField('Hero data in JSON format', 'Data')
    def __str__(self):
        return self.Name
    pass

home/views.py
from django.shortcuts import render

# Create your views here.

def StartPadge(request):
    return render(request, 'home/StartPadge.html')

match_history/views.py
from django.shortcuts import render
from django.http import HttpResponse

import requests
import datetime
import json

from match_history.models import Hero, Item

# Enter you steam dev code hire
code : str = ""
account_id : str = '196716841'

if (code == ""):
	raise Exception('Empty dev code!!')

Matches_Detail = {}
Matches = None
Heroes = None
Items = None
Yield_Detail_Process = None

class Player_Data:
	Hero_ID = 0
	Hero_Image_Path = None
	Hero_Name = None
	Kills = 0
	Assists = 0
	Deaths = 0
	Last_Hits = 0
	Denies = 0
	Gold_Per_Min = 0
	Xp_Per_Min = 0
	Level = 0
	Hero_Damage = 0
	Tower_Damage = 0
	Hero_Healing = 0
	Gold_Spent = 0

	Items_Images_Paths = []

	def __init__(self, data):
		self.Hero_ID = data['hero_id']
		self.Items_Images_Paths = list()

		self.Kills = data['kills']
		self.Assists = data['assists']
		self.Deaths = data['deaths']
		self.Last_Hits = data['last_hits']
		self.Denies = data['denies']
		self.Gold_Per_Min = data['gold_per_min']
		self.Xp_Per_Min = data['xp_per_min']
		self.Level = data['level']
		self.Hero_Damage = data['hero_damage']
		self.Tower_Damage = data['tower_damage']
		self.Hero_Healing = data['hero_healing']
		self.Gold_Spent = data['gold_spent']

		hero = next(x for x in Heroes if x['id'] == self.Hero_ID)
		hero_name = hero['name'].partition('npc_dota_hero_')[2]
		self.Hero_Image_Path = f'http://cdn.dota2.com/apps/dota2/images/heroes/{hero_name}_full.png'
		self.Hero_Name = hero['localized_name']

		items_id_list = [
			data['item_0'],
			data['item_1'],
			data['item_2'],
			data['item_3'],
			data['item_4'],
			data['item_5'],
			data['backpack_0'],
			data['backpack_1'],
			data['backpack_2'],
			data['item_neutral']
		]
		for id in items_id_list:
			if (id != 0):
				item = next(i for i in Items if i['id'] == id)
				item_name : str = item['name'].partition('item_')[2]
				if (item_name.startswith('recipe')):
					self.Items_Images_Paths.append(f'http://cdn.dota2.com/apps/dota2/images/items/recipe_lg.png')
				else:
					self.Items_Images_Paths.append(f'http://cdn.dota2.com/apps/dota2/images/items/{item_name}_lg.png')
			else:
				self.Items_Images_Paths.append(f'https://dummyimage.com/85x64/222.jpg&text=%20')
			
		pass

class Match_Data:
	Radiant_Is_Victory = True
	Duration = '00:00'
	Start_Date_Time = "01.01.2000 00:00:00"
	Radiant_Players = None
	Dire_Players = None

	def __init__(self, match_detail):

		self.Radiant_Players = list()
		self.Dire_Players = list()
		self.Radiant_Is_Victory = match_detail['radiant_win']
		duration_in_sec = match_detail['duration']
		sec = duration_in_sec % 60
		min = (duration_in_sec - sec) // 60
		hours = (duration_in_sec - sec) % 60
		self.Duration = f'{hours}:{min}:{sec}' if hours>0 else f'{min}:{sec}'
		timestamp = match_detail['start_time']
		date_time = datetime.datetime.fromtimestamp(timestamp)
		self.Start_Date_Time = date_time.strftime('%d.%m.%Y %H:%M:%S')

		players = match_detail['players']
		for data in players[:5:]:
			self.Radiant_Players.append(Player_Data(data))
		for data in players[5::]:
			self.Dire_Players.append(Player_Data(data))
		pass

def Get_Match_History_Data():
	URL : str = 'http://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/v1'
	params = {'key': code, 'account_id': account_id}
	result : str = requests.get(URL, params=params)
	return result.text

def Parce_Match_History_Data(data:str):
	History = json.loads(data)
	return History['result']['matches']

def Get_Match_Detail_Data(id):
	URL : str = 'http://api.steampowered.com/IDOTA2Match_570/GetMatchDetails/v1'
	params = { 'key':code, 'match_id':id }
	result : str = requests.get(URL, params=params)
	return result.text

def Parce_Match_Detail_Data(data):
	detail = json.loads(data)
	return detail['result']

def Get_Matches_Detail(matches):
	result_dict: dict = dict()
	for match in matches:
		id = match['match_id']
		detail_data = Get_Match_Detail_Data(id)
		match_detail = Parce_Match_Detail_Data(detail_data)
		result = Match_Data(match_detail)
		result_dict.update({id: result})
	return result_dict

def Get_Heroes():
	URL : str = 'http://api.steampowered.com/IEconDOTA2_570/GetHeroes/v1'
	language='ru'
	params = {'key':code, 'language':language }

	result = requests.get(URL, params=params)
	data = json.loads(result.text)['result']['heroes']

	return data

def Get_Items():

	URL : str = 'http://api.steampowered.com/IEconDOTA2_570/GetGameItems/v1'
	language='ru'
	params = {'key':code, 'language':language }
	
	result = requests.get(URL, params=params)
	data = json.loads(result.text)['result']['items']

	return data

def Update_Hereos(request):
	Hero.objects.all().delete()
	for hero in Get_Heroes():
		name = hero["localized_name"]
		h = Hero.objects.create(Data = hero, Name=name)
	return HttpResponse('Successfull update')

def Update_Items(request):
	Item.objects.all().delete()
	for item in Get_Items():
		i = Item.objects.create(Data = item)
	return HttpResponse('Successfull update')

def GetMatches(request, page_number):
	matches_on_page = 5
	global Matches, Matches_Detail, Heroes, Items
	if (Matches is None):
		Matches_Detail = {}
		data : str = Get_Match_History_Data()
		Matches = Parce_Match_History_Data(data)

		Heroes = [ hero.Data for hero in Hero.objects.all() ]
		Items = [ item.Data for item in Item.objects.all() ]
		
	
	start_index = matches_on_page*(page_number-1)
	end_index = matches_on_page*page_number
	Matches_Detail = Get_Matches_Detail(Matches[start_index:end_index])

	min_page_num = 1
	previous_page_num = page_number - min_page_num if page_number > min_page_num else min_page_num
	max_page_num = len(Matches)//matches_on_page
	next_page_num = page_number + 1 if page_number < max_page_num else max_page_num

	pages = [num for num in range(page_number-4, page_number+4+1) if min_page_num <= num <= max_page_num]
	
	data_dict = {
		'Matches_Detail': Matches_Detail, 
		'page_number': page_number, 
		'previous_page_num': previous_page_num, 
		'min_page_num': min_page_num,
		'max_page_num': max_page_num, 
		'next_page_num': next_page_num,
		'pages': pages,
			  }

	return render(request, 'match_history/Maches.html', data_dict)

home/templates/home/StartPadge.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Home page</title>
</head>
<body>
    <h1>Home Padge</h1>

    <a href="{% url 'Matches:GetMatches' '1' %}">Matches</a> <br />
    <a href="{% url 'Matches:update_heroes' %}">Update heroes</a> <br />
    <a href="{% url 'Matches:update_items' %}">Update items</a> <br />
    <a href="admin">Admin panel</a> <br />
</body>
</html>

match_history/templates/match_history/Maches.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Matches</title>
    <link rel="stylesheet" href="{% static  'css/My_Styles.css' %}">
</head>
<body>
    <h1>Page {{page_number}}</h1>
    {% for key, value in Matches_Detail.items %}
    <section>
        <h2>Match {{key}}</h2>
        <h3>{{value.Start_Date_Time}}</h3>
        {% if value.Radiant_Is_Victory %}
        <h3>Victory of the forces of light</h3>
        {% else %}
        <h3>Victory of the forces of darkness</h3>
        {% endif %}
        <h3>{{value.Duration}}</h3>
        <table>
            <caption><h3>"Radiant" team</h3></caption>
            <thead>
                <tr>
                    <th>Hero</th>
                    <th>Inventory</th>
                    <th>Neutral item</th>
                    <th>Kills</th>
                    <th>Deaths</th>
                    <th>Assists</th>
                    <th>Last hits</th>
                    <th>Denies</th>
                    <th>GPM</th>
                    <th>OPM</th>
                    <th>Level</th>
                    <th>Hero damage</th>
                    <th>Tower damage</th>
                    <th>Hero healing</th>
                    <th>Gold spent</th>
                </tr>
            </thead>
            <tbody>
            {% for player in value.Radiant_Players %}
                <tr>
                    <td>
                        <img src="{{player.Hero_Image_Path}}" width="256" height="144">
                    </td>

                    <td class="inventory" width="250">
                        <img class="active item" src="{{player.Items_Images_Paths.0}}" width="51"/>
                        <img class="active item" src="{{player.Items_Images_Paths.1}}" width="51"/>
                        <img class="active item" src="{{player.Items_Images_Paths.2}}" width="51"/>
                        <br />
                        <img class="active item" src="{{player.Items_Images_Paths.3}}" width="51"/>
                        <img class="active item" src="{{player.Items_Images_Paths.4}}" width="51"/>
                        <img class="active item" src="{{player.Items_Images_Paths.5}}" width="51"/>
                        <br />
                        <img class="backpack item" src="{{player.Items_Images_Paths.6}}" width="51"/>
                        <img class="backpack item" src="{{player.Items_Images_Paths.7}}" width="51"/>
                        <img class="backpack item" src="{{player.Items_Images_Paths.8}}" width="51"/>
                    </td>

                    <td>
                        <div class="neutral item" style="background-image:url({{player.Items_Images_Paths.9}}); width:38px; height:38px;"></div>
                    </td>

                    <td>
                        <div class="kills stat">{{player.Kills}}</div>
                    </td>
                    
                    <td>
                        <div class="deaths stat">{{player.Deaths}}</div>
                    </td>

                    <td>
                        <div class="assists stat">{{player.Assists}}</div>
                    </td>
                    
                    <td>
                        <div class="last_hits stat">{{player.Last_Hits}}</div>
                    </td>

                    <td>
                        <div class="denies stat">{{player.Denies}}</div>
                    </td>
                    
                    <td>
                        <div class="gold_per_min stat">{{player.Gold_Per_Min}}</div>
                    </td>
                    
                    <td>
                        <div class="xp_per_min stat">{{player.Xp_Per_Min}}</div>
                    </td>
                    
                    <td>
                        <div class="level stat">{{player.Level}}</div>
                    </td>
                    
                    <td>
                        <div class="hero_damage stat">{{player.Hero_Damage}}</div>
                    </td>
                    
                    <td>
                        <div class="tower_damage stat">{{player.Tower_Damage}}</div>
                    </td>
                    
                    <td>
                        <div class="hero_healing stat">{{player.Hero_Healing}}</div>
                    </td>
                    
                    <td>
                        <div class="gold_spent stat">{{player.Gold_Spent}}</div>
                    </td>
                </tr>
                {% endfor %}

            </tbody> 
        </table>
        <table>
            <caption><h3>"Dire" team</h3></caption>
            <thead>
                <tr>
                    <th>Hero</th>
                    <th>Inventory</th>
                    <th>Neutral item</th>
                    <th>Kills</th>
                    <th>Deaths</th>
                    <th>Assists</th>
                    <th>Last hits</th>
                    <th>Denies</th>
                    <th>GPM</th>
                    <th>OPM</th>
                    <th>Level</th>
                    <th>Hero damage</th>
                    <th>Tower damage</th>
                    <th>Hero healing</th>
                    <th>Gold spent</th>
                </tr>
            </thead>
            <tbody>
                {% for player in value.Dire_Players %}
                <tr>
                    <td>
                        <img src="{{player.Hero_Image_Path}}" width="256" height="144">
                    </td>

                    <td class="inventory" width="250">
                        <img class="active item" src="{{player.Items_Images_Paths.0}}" width="51"/>
                        <img class="active item" src="{{player.Items_Images_Paths.1}}" width="51"/>
                        <img class="active item" src="{{player.Items_Images_Paths.2}}" width="51"/>
                        <br />
                        <img class="active item" src="{{player.Items_Images_Paths.3}}" width="51"/>
                        <img class="active item" src="{{player.Items_Images_Paths.4}}" width="51"/>
                        <img class="active item" src="{{player.Items_Images_Paths.5}}" width="51"/>
                        <br />
                        <img class="backpack item" src="{{player.Items_Images_Paths.6}}" width="51"/>
                        <img class="backpack item" src="{{player.Items_Images_Paths.7}}" width="51"/>
                        <img class="backpack item" src="{{player.Items_Images_Paths.8}}" width="51"/>
                    </td>

                    <td>
                        <div class="neutral item" style="background-image:url({{player.Items_Images_Paths.9}}); width:38px; height:38px;"></div>
                    </td>

                    <td>
                        <div class="kills stat">{{player.Kills}}</div>
                    </td>
                    
                    <td>
                        <div class="deaths stat">{{player.Deaths}}</div>
                    </td>

                    <td>
                        <div class="assists stat">{{player.Assists}}</div>
                    </td>
                    
                    <td>
                        <div class="last_hits stat">{{player.Last_Hits}}</div>
                    </td>

                    <td>
                        <div class="denies stat">{{player.Denies}}</div>
                    </td>
                    
                    <td>
                        <div class="gold_per_min stat">{{player.Gold_Per_Min}}</div>
                    </td>
                    
                    <td>
                        <div class="xp_per_min stat">{{player.Xp_Per_Min}}</div>
                    </td>
                    
                    <td>
                        <div class="level stat">{{player.Level}}</div>
                    </td>
                    
                    <td>
                        <div class="hero_damage stat">{{player.Hero_Damage}}</div>
                    </td>
                    
                    <td>
                        <div class="tower_damage stat">{{player.Tower_Damage}}</div>
                    </td>
                    
                    <td>
                        <div class="hero_healing stat">{{player.Hero_Healing}}</div>
                    </td>
                    
                    <td>
                        <div class="gold_spent stat">{{player.Gold_Spent}}</div>
                    </td>
                </tr>
                {% endfor %}

            </tbody> 
        </table>

    </section>
    {% endfor %}
    <section>
        <nav>
            <a href="{% url 'Matches:GetMatches' min_page_num %}">
            <input type="button" value="<<"/>
            </a>
            <a href="{% url 'Matches:GetMatches' previous_page_num %}">
            <input type="button" value="<"/>
            </a>

            {% if not min_page_num in pages %}
            <input type="button" value="..."/>
            {% endif %}

            {% for page in pages %}
                {% if page == page_number %}
                    <a class="curent_page" href="{% url 'Matches:GetMatches' page %}">
                    <input class="curent_page" type="button" value="{{page}}"/>
                    </a>
                {% else %}
                    <a href="{% url 'Matches:GetMatches' page %}">
                    <input type="button" value="{{page}}"/>
                    </a>
                {% endif %}
            {% endfor %}
            
            {% if not max_page_num in pages %}
            <input type="button" value="..."/>
            {% endif %}

            <a href="{% url 'Matches:GetMatches' next_page_num %}">
            <input type="button" value=">"/>
            </a>
            <a href="{% url 'Matches:GetMatches' max_page_num %}">
            <input type="button" value=">>"/>
            </a>
        </nav>
    </section>
</body>
</html>

match_history/templates/purchase/All.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Purchases</title>
</head>
<body>
    <h1>All</h1>
    {% for key, value in Matches_Detail.items %}
    <section>
        <h2>{{key}}</h2>
        <h5>{{value.Start_Date_Time}}</h5>
        {% if value.Radiant_Is_Victory %}
        <h5>Radiant victory</h5>
        {% else %}
        <h5>Dire victory</h5>
        {% endif %}
        <h5>{{value.Duration}}</h5>
        <table>
            <tbody>
            {% for player in value.Radiant_Players %}
                <tr>
                    <td>
                        <img src="{{player.Hero_Image_Path}}" width="256" height="144">
                    </td>

                    <td>
                        {% for path in player.Items_Images_Paths %}
                        <img src="{{path}}" width="85" height="64"/>
                        {% endfor %}
                    </td>

                    <td>
                        <div class="kills">{{player.Kills}}</div>
                    </td>

                    <td>
                        <div class="assists">{{player.Assists}}</div>
                    </td>
                    <td>
                        <div class="deaths">{{player.Deaths}}</div>
                    </td>
                    
                    <td>
                        <div class="last_hits">{{player.Last_Hits}}</div>
                    </td>

                    <td>
                        <div class="denies">{{player.Denies}}</div>
                    </td>
                    
                    <td>
                        <div class="gold_per_min">{{player.Gold_Per_Min}}</div>
                    </td>
                    
                    <td>
                        <div class="xp_per_min">{{player.Xp_Per_Min}}</div>
                    </td>
                    
                    <td>
                        <div class="level">{{player.Level}}</div>
                    </td>
                    
                    <td>
                        <div class="hero_damage">{{player.Hero_Damage}}</div>
                    </td>
                    
                    <td>
                        <div class="tower_damage">{{player.Tower_Damage}}</div>
                    </td>
                    
                    <td>
                        <div class="hero_healing">{{player.Hero_Healing}}</div>
                    </td>
                    
                    <td>
                        <div class="gold_spent">{{player.Gold_Spent}}</div>
                    </td>
                </tr>
                {% endfor %}

            </tbody> 
            <tr><td><hr/></td></tr>
            <tbody>
                {% for player in value.Dire_Players %}
                <tr>
                    <td>
                        <img src="{{player.Hero_Image_Path}}" width="256" height="144">
                    </td>

                    <td>
                        {% for path in player.Items_Images_Paths %}
                        <img src="{{path}}" width="85" height="64"/>
                        {% endfor %}
                    </td>

                    <td>
                        <div class="kills">{{player.Kills}}</div>
                    </td>

                    <td>
                        <div class="assists">{{player.Assists}}</div>
                    </td>
                    <td>
                        <div class="deaths">{{player.Deaths}}</div>
                    </td>
                    
                    <td>
                        <div class="last_hits">{{player.Last_Hits}}</div>
                    </td>

                    <td>
                        <div class="denies">{{player.Denies}}</div>
                    </td>
                    
                    <td>
                        <div class="gold_per_min">{{player.Gold_Per_Min}}</div>
                    </td>
                    
                    <td>
                        <div class="xp_per_min">{{player.Xp_Per_Min}}</div>
                    </td>
                    
                    <td>
                        <div class="level">{{player.Level}}</div>
                    </td>
                    
                    <td>
                        <div class="hero_damage">{{player.Hero_Damage}}</div>
                    </td>
                    
                    <td>
                        <div class="tower_damage">{{player.Tower_Damage}}</div>
                    </td>
                    
                    <td>
                        <div class="hero_healing">{{player.Hero_Healing}}</div>
                    </td>
                    
                    <td>
                        <div class="gold_spent">{{player.Gold_Spent}}</div>
                    </td>
                </tr>
                {% endfor %}

            </tbody> 
        </table>

    </section>
    {% endfor %}
</body>
</html>